Rocket\Clients\OrganizationsBundle\Entity\Organization:
    type: entity
    table: null
    repositoryClass: Rocket\Clients\OrganizationsBundle\Repository\OrganizationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            column: Name
        created:
            type: datetime
            column: Created
        description:
            type: text
            nullable: true
            column: Description
        owner:
            type: integer
            nullable: true
            column: Owner
    lifecycleCallbacks: {  }
