rocket_clients_organizations:
    resource: "@RocketClientsOrganizationsBundle/Resources/config/routing.yml"
    prefix:   /

rocket_clients_contacts:
    resource: "@RocketClientsContactsBundle/Resources/config/routing.yml"
    prefix:   /

rocket_expenses:
    resource: "@RocketExpensesBundle/Resources/config/routing.yml"
    prefix:   /
