upload_product:
    resource: "@UploadBundle/Controller/ProductController.php"
    type:     annotation

upload:
    resource: "@UploadBundle/Resources/config/routing.yml"
    prefix:   /upload

rocket_clients_organizations:
    resource: "@RocketClientsOrganizationsBundle/Resources/config/routing.yml"
    prefix:   /

rocket_clients_contacts:
    resource: "@RocketClientsContactsBundle/Resources/config/routing.yml"
    prefix:   /

rocket_expenses:
    resource: "@RocketExpensesBundle/Resources/config/routing.yml"
    prefix:   /
