Rocket\Clients\ContactsBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: Rocket\Clients\ContactsBundle\Repository\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        namePrefix:
            type: string
            length: 255
            nullable: true
            column: NamePrefix
        firstName:
            type: string
            length: 255
            column: FirstName
        lastName:
            type: string
            length: 255
            column: LastName
        description:
            type: text
            nullable: true
            column: Description
        emails:
            type: string
            nullable: true
            column: Emails
        phones:
            type: string
            nullable: true
            column: Phones
        twitter:
            type: string
            length: 255
            nullable: true
            column: Twitter
        facebook:
            type: string
            length: 255
            nullable: true
            column: Facebook
        linkedIn:
            type: string
            length: 255
            nullable: true
            column: LinkedIn
        jobTitle:
            type: string
            length: 255
            nullable: true
            column: JobTitle
        birthday:
            type: datetime
            nullable: true
            column: Birthday
        gender:
            type: string
            length: 255
            column: Gender
        picture:
            type: integer
            nullable: true
            column: Picture
        created:
            type: datetime
            column: Created
    lifecycleCallbacks: {  }
    manyToOne:
        organization:
            targetEntity: Rocket\Clients\OrganizationsBundle\Entity\Organization
            inversedBy: contacts
            joinColumn:
                name: organization_id
                referencedColumnName: id
